### ISSUE TITLE
Should we reduce the namespace back to just `Effect`?

### ISSUE THREAD

**Issue by garyb** [purescript/purescript-effect#1]
There has been discussion a few times of whether `Data`, `Control`, and so on is actually a useful way of grouping stuff, plus ideas about flattening the namespace a bit to match namespace with library names to try and prevent namespace collisions.

Since this is a new library, and will be introduced into the usage of the core libraries soon, it might be time to consider making the change now? Also relevant comment here: https://github.com/purescript/purescript-exceptions/pull/26#issuecomment-372022653

**Comment by hdgarrood** [comment]
If we're going to do this, I'd really, really like to do https://github.com/purescript/purescript/issues/2437 first/at the same time.

**Comment by garyb** [comment]
Well, I was thinking more that if we start doing the names first then something like that might be more practical eventually. It's a massive change in philosophy (and functionality really) to make the compiler package-aware.

**Comment by hdgarrood** [comment]
That issue is quite long, but neither of the two options we ended up with actually make the compiler package-aware, at least not in any way which ends up being particularly meaningful, either philosophically or functionally.

**Comment by garyb** [comment]
Ah my mistake, I'll re-read it.

**Comment by paf31** [comment]
Would the idea be to require package-qualified names everywhere? That seems like it would increase the library changes quite a lot. Would that be for 0.12?

**Comment by hdgarrood** [comment]
The idea wouldn't be to *require* them everywhere, but more *permit* them. But yeah, this would involve a lot of breakage - just only at the library level, so it wouldn't be a breaking change in the compiler/language. It is at least the kind of change that's quite amenable to writing a script which automatically updates your code to refer to the new module names.

Come to think of it, when (if) we do it, we could maybe re-export the new modules under the old names for a while? That would hopefully make the transition a fair bit smoother.
