### ISSUE TITLE
Mistake in the example?

### ISSUE THREAD

**Issue by ferranlala** [purescript/purescript-effect#14]
Hi, looking at the example on the README:

```javascript
// Counter.js
exports.incrCounter = function() {
  if (!window.globalCounter) {
    window.globalCounter = 0;
  }
  return ++window.globalCounter;
}
```

and then looking at the implementation of pure, shouldn't `incrCounter` be thunked?:

```javascript
// Counter.js
exports.incrCounter = function() {
  return function() {
    if (!window.globalCounter) {
      window.globalCounter = 0;
    }
    return ++window.globalCounter;
  }
}
``` 

I'm trying to figure out how Effect works, so my apologies in advance if this It's just me not understanding properly.

**Comment by natefaubion** [comment]
It is already thunked with the outer `function () { }`.

**Comment by ferranlala** [comment]
Ah ok! Sorry I misread the signature as

`foreign import incrCounter :: Unit -> Effect Int`.

Now I see it is `foreign import incrCounter :: Effect Int` and everything makes sense. Thank you.
