### ISSUE TITLE
Add a way to defer an effect

### ISSUE THREAD

**Issue by natefaubion** [purescript/purescript-effect#16]
Due to strict evaluation, if a function takes an `Effect a` as an argument, it's often desirable to defer evaluation under a lambda literal, particularly if there are non-trivial let bindings.

```purescript
example = doThis do
  let foo = ...
  let bar = ...
  doThat foo bar
```

This will likely evaluate foo/bar in the process of _allocating_ the effect. If there was a `Lazy` instance, one could do:

```purescript
example = doThis $ defer \_ -> do
  let foo = ...
  let bar = ...
  doThat foo bar
```

Definitely deferring evaluation of foo/bar until the effect is actually invoked. We can't implement an instance for Lazy (control depends on effect), and this module doesn't export this as a primitive so the implementation would need to rely on unsafeCoerce.

Proposed implementation:
```purescript
foreign import defer :: forall a. (Unit -> Effect a) -> Effect a
```
```javascript
exports.defer = function(k) {
  return function() {
    return k()();
  };
};
```

**Comment by hdgarrood** [comment]
Sounds reasonable to me 👍 could we add a Lazy instance downstream if we did this, then?

**Comment by natefaubion** [comment]
Yes.

**Comment by natefaubion** [comment]
I guess it could be implemented as:
```
defer k = pure unit >>= k
```
Not sure if there's any difference.

**Comment by natefaubion** [comment]
I think it's fine to do it that way, I was thinking too hard 😆
