### ISSUE TITLE
Re-export `liftEffect`

### ISSUE THREAD

**Issue by klntsky** [purescript/purescript-effect#19]
`liftEffect` is commonly used, I believe it would be better to re-export it from `Effect.Class` in `Effect` module, instead of having to type this:

```purescript
import Effect (Effect)
import Effect.Class (liftEffect)
```

**Comment by hdgarrood** [comment]
I think if we were going to do this we might as well merge the whole Effect.Class module into the Effect module, since the former only contains MonadEffect and liftEffect.

**Comment by hdgarrood** [comment]
To clarify: while I would support merging the Effect.Class module into the Effect module if backwards compatibility were not a concern, unfortunately it is, so I don't think we should do this.

**Comment by hdgarrood** [comment]
Ok, so on reflection, I think the options are:
1. Leave the Effect.Class module as-is and re-export MonadEffect and liftEffect from the Effect module
2. move MonadEffect and liftEffect into the Effect module, and re-export deprecated versions of them from the Effect.Class module, to be removed in a future release
3. Do nothing

and I think 2) is difficult to justify, but I'd be ok with 1).

**Comment by JordanMartinez** [comment]
Why is backwards compatibility a concern here? Is it because there are compiler optimizations going on behind-the-scenes that would indirectly affect this change?

**Comment by kl0tl** [comment]
We cannot re-export MonadEffect and liftEffect from the Effect module because of the circular dependency it would incur. I don’t think we should pursue this anymore: *.Class modules are a common pattern already and we have tooling to help with imports.

**Comment by hdgarrood** [comment]
Backwards compatibility is a concern because it is frustrating when you have to make changes to code which previously worked fine in order to use a new release, especially if the change is perceived as unnecessary (which I’m sure this would be by some users).

**Comment by JordanMartinez** [comment]
If we're not going to make this change now, would we ever make this change in the future? For example, if we wanted to clean up the API around numerous libraries just so things are more ergonomic from that point forward? Or has the ship already sailed?

**Comment by hdgarrood** [comment]
I can imagine doing this if we ever get around to doing the thing where package names become part of module names (which requires breaking absolutely everything, albeit in a way that we could automatically fix), but otherwise probably not.

**Comment by JordanMartinez** [comment]
Gotcha. Could we tag this issue with something related to the package-aware change, so that we know to make such a breaking change when it occurs?

**Comment by hdgarrood** [comment]
I'm not sure it's worth it, really; we'll have to remember to check that tag (if it exists) and if it's only used in a few places that seems equally unlikely as just remembering about this proposed change organically.

**Comment by JordanMartinez** [comment]
That makes sense. 

I'm in favor or not making a breaking change here then as the cost incurs doesn't seem worth the benefit, at least for right now.
