### ISSUE TITLE
Stack safety?

### ISSUE THREAD

**Issue by safareli** [purescript/purescript-effect#9]
Is there any interest in porting https://github.com/purescript/purescript-eff/pull/31 here?

**Comment by hdgarrood** [comment]
Sorry that got missed. It's not just up to me, but I do think it's worth considering -- especially as the implementation you ended up with seems pretty straightforward too. :+1:

**Comment by hdgarrood** [comment]
I’m going to close this as, after discussion in #12, it sounds like this isn’t something we want to pursue after all.
